basePath: /api/v1/
definitions:
  models.AvailableSelection:
    description: Market with available betting options
    properties:
      market:
        type: string
      selections:
        items:
          properties:
            handicap:
              type: string
            name:
              type: string
            odds:
              type: number
          type: object
        type: array
    type: object
  models.BetEvaluationRequest:
    description: Request body for evaluating a betting selection
    properties:
      handicap:
        type: string
      market:
        type: string
      score_line:
        description: Add this for correct score
        type: string
      selection:
        type: string
    type: object
  models.BetSelection:
    description: Concrete betting selection with all required parameters
    properties:
      handicap:
        type: string
      market:
        type: string
      odds:
        type: number
      score_line:
        type: string
      selection:
        type: string
    type: object
  models.EvaluationResult:
    description: Result of evaluating a betting selection
    properties:
      actual_result:
        type: string
      description:
        type: string
      outcome:
        type: string
      selection:
        $ref: '#/definitions/models.BetSelection'
    type: object
host: localhost:8080
info:
  contact:
    email: yaredyemane1@gmail.com
    name: API Support
  description: API for evaluating betting selections against match results
  license:
    name: Yared Yemane
  title: Betting Evaluation API
  version: "1.0"
paths:
  /evaluate:
    post:
      consumes:
      - application/json
      description: Evaluates a specific betting selection against the match results
      parameters:
      - description: Bet selection to evaluate
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BetEvaluationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Evaluation result with outcome
          schema:
            $ref: '#/definitions/models.EvaluationResult'
        "400":
          description: Invalid request body or parameters
          schema:
            type: object
        "404":
          description: No result data available
          schema:
            type: object
      summary: Evaluate a betting selection
      tags:
      - Evaluation
  /selections:
    get:
      consumes:
      - application/json
      description: Retrieves all available betting markets and selections from prematch
        data
      produces:
      - application/json
      responses:
        "200":
          description: List of available selections grouped by market
          schema:
            items:
              $ref: '#/definitions/models.AvailableSelection'
            type: array
        "404":
          description: No prematch data available
          schema:
            type: object
      summary: Get available betting selections
      tags:
      - Selections
swagger: "2.0"
